export const PrimaryPink = "#D82387"
export const SecondaryPink = "#FBDBE9"
export const PrimaryBlue = "#785BA3"
export const SecondaryBlue = "#E3CFFD"
export const LightGray = "#F6F6F6"
export const FieldBackground = "#F8F4FF"
