// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Blobs                      string
	Cities                     string
	FollowerUsersFollowedUsers string
	Hubs                       string
	IssuedTokens               string
	Messages                   string
	SchemaMigrations           string
	Users                      string
}{
	Blobs:                      "blobs",
	Cities:                     "cities",
	FollowerUsersFollowedUsers: "follower_users_followed_users",
	Hubs:                       "hubs",
	IssuedTokens:               "issued_tokens",
	Messages:                   "messages",
	SchemaMigrations:           "schema_migrations",
	Users:                      "users",
}
