// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Blobs            string
	Cities           string
	Hubs             string
	IssuedTokens     string
	Messages         string
	SchemaMigrations string
	Users            string
}{
	Blobs:            "blobs",
	Cities:           "cities",
	Hubs:             "hubs",
	IssuedTokens:     "issued_tokens",
	Messages:         "messages",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
